# Generated by Django 4.2.27 on 2026-08-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('NSS', 'NSS (National Service Scheme)'), ('CULTURAL', 'Cultural Activities'), ('SPORTS', 'Sports & Games'), ('INTERNSHIP', 'Internship & Training'), ('WORKSHOP', 'Workshops & Seminars'), ('HACKATHON', 'Hackathons & Competitions'), ('COURSES', 'Online Certifications (NPTEL/Coursera/SWAYAM)'), ('RESEARCH', 'Research Papers & Patents'), ('INDUSTRIAL_VISIT', 'Industrial Visits'), ('OTHER', 'Other Extracurricular Achievements')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='category', max_length=50)),
                ('color_class', models.CharField(default='primary', max_length=50)),
                ('target_points', models.PositiveIntegerField(default=25, help_text='Target points needed for 100% completion in this category')),
                ('weight_percentage', models.PositiveIntegerField(default=10, help_text='Weightage in overall progress formula')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150)),
                ('default_points', models.PositiveIntegerField(default=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='activities.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('event_date', models.DateField()),
                ('level', models.CharField(choices=[('COLLEGE', 'College / Institutional'), ('DISTRICT', 'District Level'), ('STATE', 'State Level'), ('NATIONAL', 'National Level'), ('INTERNATIONAL', 'International Level')], default='COLLEGE', max_length=30)),
                ('achievement_role', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('WINNER', '1st Prize / Winner'), ('RUNNER_UP', 'Runner Up / 2nd-3rd Place'), ('VOLUNTEER', 'Volunteer / Organizer'), ('COMPLETED', 'Successfully Completed')], default='PARTICIPANT', max_length=30)),
                ('certificate_file', models.FileField(upload_to='activity_certs/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Verified & Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('faculty_remark', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='activities.activitycategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_certificates', to='students.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_activity_certs', to='accounts.facultyprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
