# Generated by Django 4.2.27 on 2026-08-14 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='stars', max_length=50)),
                ('badge_color', models.CharField(default='gold', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalNOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('noc_id', models.CharField(max_length=50, unique=True)),
                ('purpose', models.CharField(default='Semester Exam & Academic Clearance', max_length=200)),
                ('library_clearance', models.BooleanField(default=True, verbose_name='Library Clearance')),
                ('academic_clearance', models.BooleanField(default=True, verbose_name='Academic Clearance')),
                ('department_clearance', models.BooleanField(default=True, verbose_name='Department Clearance')),
                ('lab_clearance', models.BooleanField(default=True, verbose_name='Lab / Workshop Clearance')),
                ('fees_clearance', models.BooleanField(default=True, verbose_name='Accounts / Fees Clearance')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='noc/qr/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='noc/pdf/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nocs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noc_requests', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('cert_type', models.CharField(choices=[('PERFECT_SUBMISSION', 'Perfect Submission Certificate'), ('ACADEMIC_EXCELLENCE', 'Academic Excellence Certificate'), ('NSS_EXCELLENCE', 'NSS Excellence Certificate'), ('CULTURAL_EXCELLENCE', 'Cultural Excellence Certificate'), ('SPORTS_EXCELLENCE', 'Sports Excellence Certificate'), ('ACTIVITY_CHAMPION', 'Activity Champion Certificate'), ('ALL_ROUNDER', 'Best All-Rounder Student Certificate'), ('SEMESTER_TOPPER', 'Semester Topper Certificate')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('achievement_text', models.TextField()),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qr/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/')),
                ('is_verified', models.BooleanField(default=True)),
                ('issued_by', models.CharField(default='EduTrack 360 Institute of Engineering & Technology', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_students', to='certificates.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
