# Generated by Django 4.2.27 on 2026-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_number', models.PositiveSmallIntegerField(unique=True)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['year_number'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duration_years', models.PositiveIntegerField(default=4)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('roman_name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('credits', models.PositiveIntegerField(default=4)),
                ('syllabus_summary', models.TextField(blank=True, null=True)),
                ('assignment_weight', models.PositiveIntegerField(default=30, help_text='Weightage percentage for Assignments (e.g. 30%)')),
                ('microproject_weight', models.PositiveIntegerField(default=30, help_text='Weightage percentage for Microprojects (e.g. 30%)')),
                ('practical_weight', models.PositiveIntegerField(default=25, help_text='Weightage percentage for Practicals (e.g. 25%)')),
                ('ppt_manual_weight', models.PositiveIntegerField(default=15, help_text='Weightage percentage for PPT/Manual (e.g. 15%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('MICROPROJECT', 'Microproject'), ('PPT', 'Presentation (PPT)'), ('MANUAL', 'Lab Manual'), ('PRACTICAL', 'Practical Work'), ('REPORT', 'Project Report'), ('VIVA', 'Viva / Demo')], default='ASSIGNMENT', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('task_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_marks', models.PositiveIntegerField(default=25)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_resources/')),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['task_type', 'task_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='submissions/')),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('faculty_remark', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
