# Generated by Django 4.2.27 on 2026-08-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='accounts.facultyprofile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.subjecttask'),
        ),
        migrations.AddField(
            model_name='subjecttask',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to='accounts.facultyprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='division',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='academics.branch'),
        ),
        migrations.AddField(
            model_name='division',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='branch',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='branch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='academics.program'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('task', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('branch', 'semester', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('branch', 'semester', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('program', 'code')},
        ),
    ]
